/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gui_GUI */

#ifndef _Included_gui_GUI
#define _Included_gui_GUI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gui_GUI
 * Method:    launchGUI
 * Signature: ([[C)V
 */
JNIEXPORT void JNICALL Java_gui_GUI_launchGUI
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
