/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class GUI */

#ifndef _Included_GUI
#define _Included_GUI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GUI
 * Method:    launchGUI
 * Signature: ([[C)V
 */
JNIEXPORT void JNICALL Java_GUI_launchGUI
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
